version: '3'
services:
  server:
    container_name: server
    tty: true
    volumes:
      - .:/server:cached
      - /server/node_modules
    ports:
      - 6000

  db:
    image: postgres:14.4
    container_name: db
    ports:
      - 3306
    volumes:
      - ./db/init:/docker-db.d
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: postgres
    restart: always
    user: root