version: '3'
services:
  server:
    build: 
      context: .
      dockerfile: ./Dockerfiles/e2e.Dockerfile
    env_file:
      - ./.env.test
    working_dir: /server
    volumes:
      - server_data:/server

volumes:
  server_data: