version: '3'
services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: ./Dockerfiles/prod.Dockerfile
    tty: true
    working_dir: /app
    depends_on:
      - db
    ports:
      - 7000:7000
    env_file:
      - .env

  db:
    image: postgres:14.4
    container_name: db
    ports:
      - 5432:5432
    environment:
      TZ: Asia/Tokyo
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    restart: always
    hostname: db
    user: root