name: e2e test
on:
   pull_request:
      branches:
         - dev

jobs:
   E2E:
      name: run e2e test
      runs-on: ubuntu-latest
      timeout-minutes: 3
      steps:
         - name: Checkout branch
           uses: actions/checkout@v3
           with:
            ref: ${{ github.event.pull_request.head.sha }}

         - name: run test on docker-compose
           run: docker compose -f docker-compose.yml -f docker-compose.e2e.yml up --abort-on-container-exit